### ISSUE TITLE
Question, possible privilege escalation issue.

### ISSUE THREAD

**Issue by andrewcorr** [kubernetes/pod-security-admission#14]
Hi, 
if a user has permissions to edit their own namespace this creates the possibility to override the PSA policy (e.g. set it to privileged)  for that namespace. Can we block this at the cluster level and only allow setting the policy globally?

Regds
AC

**Comment by liggitt** [comment]
You can set cluster-wide PSA defaults with kube-apiserver configuration (see https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/#configure-the-admission-controller), but write permission to change labels on a namespace _does_ allow changing the PSA level of that namespace.

You can either avoid granting namespace update permissions to untrusted users, or create a [validating admission policy](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#creating-a-validatingadmissionpolicy) to prevent setting a PSA enforce label on any namespace. Something like this:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "namespace-psa-policy.example.com"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["namespaces"]
  variables:
    - name: enforceLevel
      expression: "object.?metadata.labels['pod-security.kubernetes.io/enforce'].orValue('')"
  validations:
    - expression: "enforceLevel == '' || enforceLevel == 'restricted'"
      message: "the pod-security.kubernetes.io/enforce label must be unset or 'restricted'"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "namespace-psa-binding-test.example.com"
spec:
  policyName: "namespace-psa-policy.example.com"
  validationActions: [Deny]
```
