### ISSUE TITLE
Message ends abruptly for seLinuxOptions check

### ISSUE THREAD

**Issue by realshuting** [kubernetes/pod-security-admission#8]
If I configure the `test` namespace to enforce `baseline` PSS checks, the return message  ends abruptly for `seLinuxOptions`:

```
$ k label ns test pod-security.kubernetes.io/enforce-version=v1.24 pod-security.kubernetes.io/enforce=baseline

$ k apply -f resources.yaml -n test

Error from server (Forbidden): error when creating "resources.yaml": pods "badpod01" is forbidden: violates PodSecurity "baseline:v1.24": seLinuxOptions (pod set forbidden securityContext.seLinuxOptions: )
```

The resource manifest that can be used to reproduce:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: badpod01
  annotations:
    container.apparmor.security.beta.kubernetes.io/initcontainer01: runtime/default
spec:
  hostNetwork: false
  hostPID: false
  hostIPC: false
  initContainers:
  - name: initcontainer01
    image: dummyimagename
    ports:
    - containerPort: 8888
      # hostPort: 53
    securityContext:
      seLinuxOptions:
        type: "container_t"
      seccompProfile:
        type: RuntimeDefault
      privileged: false
      capabilities:
        add:
        - CHOWN
  containers:
  - name: container01
    image: dummyimagename
    ports:
    - containerPort: 8888
      hostPort: 0
    securityContext:
      seLinuxOptions:
        type: container_t
        # user: sysadm_u
      privileged: false
      capabilities:
        add:
        - DAC_OVERRIDE
        - SYS_CHROOT 
    # volumeMounts:
    #   - name: udev
    #     mountPath: /data
  securityContext:
    seLinuxOptions:
      user: sysadm_u
      # type: spc_t
    windowsOptions:
      hostProcess: false
  volumes:
  # - name: udev
  #   hostPath:
  #     path: /etc/udev
  - name: temp
    emptyDir: {}
```
